FROM python:3.12-slim

WORKDIR /app

COPY ./data /app
COPY ./data/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "receiver:extractor", "--host", "0.0.0.0", "--port", "8000", "--reload"]
